config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root 'pages#home'
  get'about', to: 'pages#about'
  resources :articles
  get 'signup', to: 'users#new'
  # post 'users', to: 'users#create'
  resources :users, except: [:new]

  # login routes with sessions
  get 'login', to:'sessions#new'
  post 'login', to:'sessions#create'
  delete 'logout', to:'sessions#destroy'

  resources :categories, except: [:destroy]
end

app/models/article.rb
class Article < ApplicationRecord
  belongs_to :user
  has_many :article_categories
  has_many :categories, through: :article_categories
  validates :title, presence: true, length: { minimum: 6, maximum: 100}
  validates :description, presence: true, length: { minimum: 10, maximum: 300}
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  # Does this action before anything else
  before_action :set_article, only: [:show, :edit, :update, :destroy]
  before_action :require_login, except: [:show,:index] # Ensures a user is logged in to perform other actions except show and index
  before_action :require_same_user, only: [:edit, :update, :destroy] # Ensures a user can only edit, update or delete their own articles
  def show
  end

  def index
    # @articles = Article.all
    @articles = Article.paginate(page: params[:page], per_page: 5)

  end

  def new
    @article = Article.new
  end

  def edit
  end

  def create
    # render plain: params[:article]
    @article = Article.new(article_params) # This is whitelisting the top level key :article, and it's containing data :title and :description
    # render plain: @article.inspect # To view entered article
    
    # Assigning a new user to the article to test the association and give illusion of authentication
    # This is for testing purposes only, in a real application, the user would be assigned automatically
    @article.user = current_user

    if @article.save
      # redirect_to article_path(@article) # Redirect show page
      flash[:notice] = "Article was created successfully" # A flash message, there is also :alert type
      redirect_to @article # Redirect show page, more concise
    else
      render :new
    end
  end

  def update
    if @article.update(article_params) # This is whitelisting the top level key :article, and it's containing data :title and :description
      flash[:notice] = "Article was updated successfully" # A flash message, there is also :alert type
      redirect_to @article
    else
      render :edit
    end
  end

  def destroy
    @article.destroy
    redirect_to articles_path
  end

  private

  def set_article
    @article = Article.find(params[:id])
  end

  def article_params
    params.require(:article).permit(:title, :description, category_ids: []) # This is whitelisting the top level key :article, and it's containing data :title and :description
  end

  # This is defined in the articles controller because it's only used in the articles controller
  def require_same_user
    if current_user != @article.user && !current_user.admin?
      flash[:alert] = "You can only perform that action on your own article"
      redirect_to @article
    end
  end
end

app/views/articles/_article.html.erb
<% obj.each do |article| %>
    <div class="row justify-content-md-center">
      <div class="col-8 mt-4">
        <div class="card text-center shadow mb-5 bg-body rounded">
          <div class="card-header fst-italic">
            <% if article.user %>
                By <%= link_to article.user.username, user_path(article.user)%>
            <%end%>
            <% if article.categories.any? %>
             <%# # render the categories partial %>
            <p><%= render article.categories%></p>
          <% end %>
                
          </div>
          <div class="card-body">
            <h5 class="card-title"><%= link_to article.title, article_path(article), class: "text-success" %></h5>
            <p class="card-text"><%= truncate(article.description, length: 100) %></p>
            <a> <%=link_to 'View', article_path(article), class:"btn btn-outline-success"%></a>
            <% if logged_in? && (article.user == current_user || current_user.admin?)%>
            <%=link_to 'Edit', edit_article_path(article), class:"btn btn-outline-info"%>
            <%= link_to 'Delete', article_path(article), method: :delete, data: { confirm: "Are you sure?" }, class: "btn btn-outline-danger" %>
            <% end %>
          </div>
          <div class="card-footer text-muted">
            <small>Created <%= time_ago_in_words(article.created_at)%> ago, edited <%= time_ago_in_words(article.updated_at)%> ago </small>
          </div>
        </div>
      </div>
    </div>
  <% end %>

app/views/articles/_form.html.erb
<div class="container"></div>
<div class="row justify-content-center">
  <div class="col-10">
    <%= render 'shared/errors', obj: @article%>
    <%= form_with(model: @article,class:"shadow p-3 mb-5 bg-body rounded", local: true)  do |form| %>
      <div class="mb-3">
        <%= form.label :title, class:"form-label"%>
        <%= form.text_field :title, class:"form-control", id:"title", placeholder:"Article Title"%>
      </div>
      <div class="mb-3">
        <%= form.label :description, class:"form-label"%>
        <%= form.text_area :description, class:"form-control", id:"description",rows:"3", placeholder:"Article Description"%>
      </div>
      <div class="mb-3">
        <%= form.label :category, class:"form-label"%>
        <%= form.collection_select :category_ids, Category.order(:name), :id, :name, { prompt: "Please select category (Can be empty)", include_hidden: false }, 
                        { multiple: true, class: "form-control custom-select shadow-rounded" } %>
      </div>
      <div class="mb-3">
        <%= form.submit class:"btn btn-primary"%>
      </div>
    <% end %>
  </div>
</div>
<div class="text-center">
  <%= link_to 'Return to Articles listing', articles_path, class: "btn btn-dark btn-lg" %>
</div>
</div>

app/views/articles/edit.html.erb
<div class="container">
  <h1 class="text-center mt-4">Edit article</h1>
  <%= render 'form'%>
</div>

app/views/articles/index.html.erb
  
<h1 class="text-center mt-4">Show all articles</h1>
<div class="container">
  <div class="flickr_pagination">
    <%= will_paginate @articles, :container => false %>
  </div>

  <%= render 'article', obj: @articles%>
  
  <div class="flickr_pagination mb-4">
    <%= will_paginate @articles, :container => false %>
  </div>

</div>

app/views/articles/new.html.erb
<div class="container">
  <h1 class="text-center mt-4">Create article</h1>
  <%= render 'form'%>
</div>

app/views/articles/show.html.erb
<h1 class="text-center mt-4"><%= @article.title %></h1>
<div class="container">
  <div class="row justify-content-md-center">
    <div class="col-8 mt-4">
      <div class="card text-center shadow mb-5 bg-body rounded">
        <div class="card-header fst-italic">
          By <%= @article.user.username if @article.user %>
          <%= link_to gravatar_for(@article.user), user_path(@article.user) %>
          <% if @article.categories.any? %>
             <%# # render the categories partial %>
            <%= render @article.categories%>
          <% end %>
        </div>
        <div class="card-body">
          <div class="card-text text-start"><%= simple_format(@article.description) %></div>
          <% if logged_in? && @article.user == current_user %>
          <a> <%=link_to 'Edit', edit_article_path(@article), class:"btn btn-outline-info"%></a>
          <%= link_to 'Delete', article_path(@article), method: :delete, data: { confirm: "Are you sure?" }, class: "btn btn-outline-danger" %>
          <% end %>
        </div>
        <div class="card-footer text-muted">
          <small>Created <%= time_ago_in_words(@article.created_at)%> ago, edited <%= time_ago_in_words(@article.updated_at)%> ago </small>
        </div>
      </div>
      <div class="text-center">
  <%= link_to 'Return to Articles listing', articles_path, class: "btn btn-dark btn-lg" %>
</div>
    </div>
  </div>
</div>