config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root 'pages#home'
  get'about', to: 'pages#about'
  resources :articles
  get 'signup', to: 'users#new'
  # post 'users', to: 'users#create'
  resources :users, except: [:new]

  # login routes with sessions
  get 'login', to:'sessions#new'
  post 'login', to:'sessions#create'
  delete 'logout', to:'sessions#destroy'

  resources :categories, except: [:destroy]
end

app/models/category.rb
class Category < ApplicationRecord
  has_many :article_categories
  has_many :articles, through: :article_categories
  validates :name, presence: true, length: { minimum: 3, maximum: 30 }
  validates_uniqueness_of :name
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  before_action :require_admin, except: [:index, :show]
  before_action :set_category, only: [:show, :edit, :update, :destroy]

  def index
    # @categories = Category.all
    @categories = Category.paginate(page: params[:page], per_page: 5)
  end

  def show
    @article_categories = @category.articles.paginate(page: params[:page], per_page: 3)
  end

  def new
    @category = Category.new
  end

  def create
    @category = Category.new(category_params)
    if @category.save
      flash[:notice] = "Category was created successfully"
      redirect_to @category
    else
      render :new
    end
  end

  def edit
  end

  def update
    if @category.update(category_params)
      flash[:notice] = "Category name was updated successfully"
      redirect_to @category
    else
      render :edit
    end
  end

  private
  def category_params
    params.require(:category).permit(:name)
  end

  def require_admin
    unless logged_in? && current_user.admin?
      flash[:alert] = "Only admins can perform that action"
      redirect_to categories_path
    end
  end

  def set_category
    @category = Category.find(params[:id])
  end
end

app/views/categories/_category.html.erb
<%# <%= category.name %>
<%= link_to category.name, category_path(category), class:"badge rounded-pill bg-info text-dark mt-2 text-decoration-none" %>

app/views/categories/_form.html.erb
<div class="container">
    <div class="row justify-content-center">
        <div class="col-10">
        <%= render 'shared/errors', obj: @category %>
        <%= form_with(model: @category,class:"shadow p-3 mb-5 bg-body rounded", local: true)  do |form| %>
            <div class="mb-3">
                <%= form.label :name,"Category Name", class:"form-label"%>
                <%= form.text_field :name, class:"form-control", id:"username", placeholder:"Enter category name"%>
            </div>    
            <div class="mb-3">
                <%= form.submit class:"btn btn-primary"%>
            </div>
        <% end %>
  </div>

app/views/categories/edit.html.erb
  <h1 class="text-center mt-4">Edit Category</h1>
<%= render 'form'%>
<div class="text-center mb-3">
  <%= link_to 'Return to Category', category_path(@category), class: "btn btn-dark btn-lg" %>
</div>

app/views/categories/index.html.erb
<div class="container">
<h1 class="text-center mt-4">Categories</h1>
  <div class="flickr_pagination">
    <%= will_paginate @categories, :container => false %>
  </div>

    <% @categories.each do |category| %>
    <div class="row justify-content-md-center">
      <div class="col-4 mt-4">
        <div class="card text-center shadow mb-5 bg-body rounded">
          <div class="card-body">
            <h5 class="card-title"><%= link_to category.name, category_path(category), class: "text-success" %></h5>
          </div>
          <p class="card-text"><%= pluralize(category.articles.count,"article") %></p>
          <div class="card-footer text-muted">
            <small>Created <%= time_ago_in_words(category.created_at)%> ago, edited <%= time_ago_in_words(category.updated_at)%> ago </small>
          </div>
        </div>
      </div>
    </div>
  <% end %>
    
  <div class="flickr_pagination">
    <%= will_paginate @categories, :container => false %>
  </div>

</div>

app/views/categories/new.html.erb
  <h1 class="text-center mt-4">New Category</h1>
<%= render 'form'%>
<div class="text-center mb-3">
  <%= link_to 'Return to Category listing', categories_path, class: "btn btn-dark btn-lg" %>
</div>

app/views/categories/show.html.erb
<h1 class="text-center mt-4"><%= @category.name %></h1>

<% if logged_in? && current_user.admin? %>
  <div class="text-center mt-4">
    <%=link_to 'Edit category name', edit_category_path(@category), class:"btn btn-outline-info"%>
  </div>
<% end %>
  <h3 class="text-center mt-4"> Articles </h3>

  <div class="flickr_pagination mb-4">
    <%= will_paginate @article_categories, :container => false %>
  </div>
  
    <%= render 'articles/article', obj: @article_categories%>
  
  <div class="flickr_pagination mb-4">
    <%= will_paginate @article_categories, :container => false %>
  </div>